### ISSUE TITLE
Not able to connect 1to1 video call

### ISSUE THREAD

**Issue by KavyaHarisha** [AgoraIO/Basic-Video-Call#211]
Hi,

I am new to this SDK, I am trying to design the video application. When I search the video support libraries, I found your SDK. 
Download the sample application(Android kotlin version), which was available in github. Run the applicaion in mobile device. The application properly run in the my mobile devices(With out any build errors).  Please see the screeen shot for reference.
![Screen shot](https://user-images.githubusercontent.com/27813072/87770300-7a14d500-c83c-11ea-96f5-1104ed4aef8f.png)

The video look like blank screen nothing is showing. And I gone through the Git hub read me file their, I am not find anything like how to talk with another person on video call (1to1 video call).

Could you please help what I have to do next step for 1to1 video call.

And I observe the blelow logs:

2020-07-17 14:52:48.127 17331-17331/io.agora.kotlin.tutorials1v1vcall V/Font: Change font:1
2020-07-17 14:52:48.128 17331-17331/io.agora.kotlin.tutorials1v1vcall V/Font: Default family:android.graphics.Typeface@6f4a449d
2020-07-17 14:52:48.200 17331-17331/io.agora.kotlin.tutorials1v1vcall W/torials1v1vcal: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2020-07-17 14:52:48.200 17331-17331/io.agora.kotlin.tutorials1v1vcall W/torials1v1vcal: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-07-17 14:52:48.217 17331-17331/io.agora.kotlin.tutorials1v1vcall I/VideoChatViewActivity: checkSelfPermission android.permission.RECORD_AUDIO 22
2020-07-17 14:52:48.217 17331-17331/io.agora.kotlin.tutorials1v1vcall I/VideoChatViewActivity: checkSelfPermission android.permission.CAMERA 23
2020-07-17 14:52:48.278 17331-18450/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns1"
2020-07-17 14:52:48.278 17331-18450/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns2"
2020-07-17 14:52:48.278 17331-18450/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns3"
2020-07-17 14:52:48.278 17331-18450/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns4"
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall E/agora-jni: exception occurred at jni call safeCallIntMethod()
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err: java.lang.SecurityException: getSerial: The user 10640 does not meet the requirements to access device identifiers.
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.os.Parcel.createException(Parcel.java:2071)
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.os.Parcel.readException(Parcel.java:2039)
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.os.Parcel.readException(Parcel.java:1987)
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerialForPackage(IDeviceIdentifiersPolicyService.java:159)
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.os.Build.getSerial(Build.java:170)
2020-07-17 14:52:48.281 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at io.agora.rtc.internal.CommonUtility.isSimulator(CommonUtility.java:222)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at io.agora.rtc.internal.RtcEngineImpl.nativeJoinChannel(Native Method)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at io.agora.rtc.internal.RtcEngineImpl.joinChannel(RtcEngineImpl.java:451)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at io.agora.tutorials1v1vcall.VideoChatViewActivity.joinChannel(VideoChatViewActivity.kt:250)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at io.agora.tutorials1v1vcall.VideoChatViewActivity.initAgoraEngineAndJoinChannel(VideoChatViewActivity.kt:99)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at io.agora.tutorials1v1vcall.VideoChatViewActivity.onCreate(VideoChatViewActivity.kt:91)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.Activity.performCreate(Activity.java:7815)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.Activity.performCreate(Activity.java:7804)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3350)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7697)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-07-17 14:52:48.282 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err: Caused by: android.os.RemoteException: Remote stack trace:
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers(TelephonyPermissions.java:427)
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at com.android.internal.telephony.TelephonyPermissions.checkReadDeviceIdentifiers(TelephonyPermissions.java:359)
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:275)
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:252)
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall W/System.err:     at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage(DeviceIdentifiersPolicyService.java:67)
2020-07-17 14:52:48.283 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.kotlin.tutorials1v1vcall
2020-07-17 14:52:48.284 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.kotlin.tutorials1v1vcall
2020-07-17 14:52:48.284 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In setSpeakerphoneOn(), on: true, calling application: io.agora.kotlin.tutorials1v1vcall
2020-07-17 14:52:48.285 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.kotlin.tutorials1v1vcall
2020-07-17 14:52:48.285 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.kotlin.tutorials1v1vcall
2020-07-17 14:52:48.286 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.kotlin.tutorials1v1vcall
2020-07-17 14:52:48.286 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.kotlin.tutorials1v1vcall
2020-07-17 14:52:48.289 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns1"
2020-07-17 14:52:48.289 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns2"
2020-07-17 14:52:48.289 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns3"
2020-07-17 14:52:48.289 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns4"
2020-07-17 14:52:48.297 17331-18450/io.agora.kotlin.tutorials1v1vcall D/*WEBRTCN*: SetRenderAndroidVM
2020-07-17 14:52:48.307 17331-17331/io.agora.kotlin.tutorials1v1vcall V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
2020-07-17 14:52:48.312 17331-18450/io.agora.kotlin.tutorials1v1vcall W/VideoCapabilities: Unsupported mime video/divx
2020-07-17 14:52:48.313 17331-18450/io.agora.kotlin.tutorials1v1vcall W/VideoCapabilities: Unsupported mime video/divx311
2020-07-17 14:52:48.314 17331-18450/io.agora.kotlin.tutorials1v1vcall W/VideoCapabilities: Unsupported mime video/divx4
2020-07-17 14:52:48.317 17331-18450/io.agora.kotlin.tutorials1v1vcall W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2020-07-17 14:52:48.318 17331-18450/io.agora.kotlin.tutorials1v1vcall W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2020-07-17 14:52:48.320 17331-18450/io.agora.kotlin.tutorials1v1vcall W/VideoCapabilities: Unsupported mime video/x-ms-wmv
2020-07-17 14:52:48.320 17331-18450/io.agora.kotlin.tutorials1v1vcall W/VideoCapabilities: Unsupported mime video/x-ms-wmv
2020-07-17 14:52:48.324 17331-18443/io.agora.kotlin.tutorials1v1vcall I/AdrenoGLES: QUALCOMM build                   : 6209c5d, Ifdcc64d6e8
    Build Date                       : 12/12/19
    OpenGL ES Shader Compiler Version: EV031.27.05.03
    Local Branch                     : mybranchea1c9b4a-9e05-f149-a3b2-1458d0b52ae8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r85-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-07-17 14:52:48.324 17331-18443/io.agora.kotlin.tutorials1v1vcall I/AdrenoGLES: Build Config                     : C O 9.0.3 AArch64
2020-07-17 14:52:48.332 17331-18429/io.agora.kotlin.tutorials1v1vcall D/ViewRootImpl[VideoChatViewActivity]: windowFocusChanged hasFocus=true inTouchMode=true
2020-07-17 14:52:48.333 17331-18443/io.agora.kotlin.tutorials1v1vcall I/AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
2020-07-17 14:52:48.346 17331-18452/io.agora.kotlin.tutorials1v1vcall I/AGORA_SDK: Surface changed to width 420 height 746
2020-07-17 14:52:48.348 17331-18452/io.agora.kotlin.tutorials1v1vcall W/Gralloc3: mapper 3.x is not supported
2020-07-17 14:52:48.366 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns1"
2020-07-17 14:52:48.366 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns2"
2020-07-17 14:52:48.366 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns3"
2020-07-17 14:52:48.366 17331-17331/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "net.dns4"
2020-07-17 14:52:48.366 17331-17331/io.agora.kotlin.tutorials1v1vcall W/torials1v1vcal: Accessing hidden method Landroid/telephony/SignalStrength;->getDbm()I (greylist-max-p, reflection, allowed)
2020-07-17 14:52:48.366 17331-17331/io.agora.kotlin.tutorials1v1vcall W/torials1v1vcal: Accessing hidden method Landroid/telephony/SignalStrength;->getAsuLevel()I (greylist-max-p, reflection, allowed)
2020-07-17 14:52:48.375 17331-18450/io.agora.kotlin.tutorials1v1vcall E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2020-07-17 14:52:48.376 17331-18450/io.agora.kotlin.tutorials1v1vcall E/Camera: getCameraInfo cameraId = 0camera num = 2
2020-07-17 14:52:48.367 17331-17331/io.agora.kotlin.tutorials1v1vcall W/Thread-32: type=1400 audit(0.0:2327530): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=18923 scontext=u:r:untrusted_app_27:s0:c128,c258,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
2020-07-17 14:52:48.377 17331-17331/io.agora.kotlin.tutorials1v1vcall I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.kotlin.tutorials1v1vcall

If I am wrong in any where in my implementation please correct me.

**Comment by plutoless** [comment]
looks like you are missing some privileges. are you sure you have granted all necessary permissions?

**Comment by lhholylight** [comment]
2020-07-28 16:41:00.737 8025-8025/io.agora.tutorials1v1vcall D/ZrHung.AppEyeUiProbe: notify runnable to start.
2020-07-28 16:41:00.746 8025-8045/io.agora.tutorials1v1vcall D/ZrHung.AppEyeUiProbe: restart watching
2020-07-28 16:41:00.832 8025-8073/io.agora.tutorials1v1vcall D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-07-28 16:41:00.863 8025-14980/io.agora.tutorials1v1vcall D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-07-28 16:41:00.865 8025-14980/io.agora.tutorials1v1vcall I/AGORA_SDK: Surface changed to width 336 height 450
2020-07-28 16:41:00.866 8025-8025/io.agora.tutorials1v1vcall W/InputMethodManager: startInputReason = 1
2020-07-28 16:41:00.879 8025-14980/io.agora.tutorials1v1vcall E/BpSurfaceComposerClient: Failed to transact (-1)
2020-07-28 16:41:00.880 8025-14980/io.agora.tutorials1v1vcall E/BpSurfaceComposerClient: Failed to transact (-1)
2020-07-28 16:41:00.993 8025-8025/io.agora.tutorials1v1vcall I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2020-07-28 16:41:06.711 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: playSoundEffect   effectType: 0
2020-07-28 16:41:06.711 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: querySoundEffectsEnabled...
2020-07-28 16:41:06.718 8025-14980/io.agora.tutorials1v1vcall W/libEGL: EGLNativeWindowType 0x72c4107010 disconnect failed
2020-07-28 16:41:06.719 8025-8025/io.agora.tutorials1v1vcall I/SurfaceView: delay destroy surface control
2020-07-28 16:41:06.730 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: isBluetoothScoOn...
2020-07-28 16:41:06.774 8025-8073/io.agora.tutorials1v1vcall E/SurfaceView: surfacePositionLost_uiRtSync  mSurfaceControl = null
2020-07-28 16:41:06.776 8025-8025/io.agora.tutorials1v1vcall I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2020-07-28 16:41:06.822 8025-8050/io.agora.tutorials1v1vcall V/AudioManager: setMode  mode: 0
2020-07-28 16:41:06.866 8025-8048/io.agora.tutorials1v1vcall D/*WEBRTCN*: SetRenderAndroidVM
2020-07-28 16:41:06.942 8025-8050/io.agora.tutorials1v1vcall I/AudioManager: setMode mode:0
2020-07-28 16:41:09.052 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: playSoundEffect   effectType: 0
2020-07-28 16:41:09.052 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: querySoundEffectsEnabled...
2020-07-28 16:41:09.071 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: isSpeakerphoneOn: true
2020-07-28 16:41:09.072 8025-8025/io.agora.tutorials1v1vcall I/chatty: uid=11172(io.agora.tutorials1v1vcall) identical 1 line
2020-07-28 16:41:09.072 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: isSpeakerphoneOn: true
2020-07-28 16:41:09.073 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: setSpeakerphoneOn  on: false
2020-07-28 16:41:09.075 8025-8025/io.agora.tutorials1v1vcall I/AudioManager: setSpeakerphoneOn on:false
2020-07-28 16:41:09.075 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: setSpeakerphoneOn  on: true
2020-07-28 16:41:09.076 8025-8025/io.agora.tutorials1v1vcall I/AudioManager: setSpeakerphoneOn on:true
2020-07-28 16:41:09.077 8025-8025/io.agora.tutorials1v1vcall V/AudioManager: isSpeakerphoneOn: true
2020-07-28 16:41:09.091 8025-8025/io.agora.tutorials1v1vcall E/libc: Access denied finding property "net.dns1"
2020-07-28 16:41:09.091 8025-8025/io.agora.tutorials1v1vcall E/libc: Access denied finding property "net.dns2"
2020-07-28 16:41:09.092 8025-8025/io.agora.tutorials1v1vcall E/libc: Access denied finding property "net.dns3"
2020-07-28 16:41:09.092 8025-8025/io.agora.tutorials1v1vcall E/libc: Access denied finding property "net.dns4"
2020-07-28 16:41:09.107 8025-17003/io.agora.tutorials1v1vcall V/AudioManager: getProperty  key: android.media.property.OUTPUT_SAMPLE_RATE
2020-07-28 16:41:09.109 8025-17003/io.agora.tutorials1v1vcall V/AudioManager: getStreamMaxVolume  treamType: 0
2020-07-28 16:41:09.109 8025-8048/io.agora.tutorials1v1vcall D/*WEBRTCN*: SetRenderAndroidVM
2020-07-28 16:41:09.139 8025-8025/io.agora.tutorials1v1vcall W/ahpl_main: type=1400 audit(0.0:1435329): avc: denied { node_bind } for scontext=u:r:untrusted_app:s0:c148,c260,c512,c768 tcontext=u:object_r:node:s0 tclass=rawip_socket permissive=0
2020-07-28 16:41:09.154 8025-17002/io.agora.tutorials1v1vcall D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-07-28 16:41:09.156 8025-17002/io.agora.tutorials1v1vcall I/AGORA_SDK: Surface changed to width 336 height 450

**Comment by plutoless** [comment]
@lhholylight the logs looks ok. is there anything i can help here?

**Comment by KavyaHarisha** [comment]
Hi,

It's was working fine now. I close this issue and thank you.
