### ISSUE TITLE
Group Video sample crash - Android

### ISSUE THREAD

**Issue by ArcherEmiya05** [AgoraIO/Basic-Video-Call#226]
Getting a crash after switching the display mode by double tap. A RecyclerView management issue?

`E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
        at java.util.ArrayList.get(ArrayList.java:310)
        at io.agora.openvcall.ui.layout.GridVideoViewContainerAdapter.getItem(GridVideoViewContainerAdapter.java:92)
        at io.agora.openvcall.ui.layout.GridVideoViewContainer.getItem(GridVideoViewContainer.java:101)
        at io.agora.openvcall.ui.CallActivity.onBigVideoViewDoubleClicked(CallActivity.java:186)
        at io.agora.openvcall.ui.CallActivity.access$100(CallActivity.java:56)
        at io.agora.openvcall.ui.CallActivity$1.onItemDoubleClick(CallActivity.java:153)
        at io.agora.propeller.ui.RecyclerItemClickListener$1.onDoubleTap(RecyclerItemClickListener.java:62)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:563)
        at io.agora.propeller.ui.RecyclerItemClickListener.onInterceptTouchEvent(RecyclerItemClickListener.java:75)
        at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2932)
        at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2978)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2150)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2422)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1754)
        at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526bproceed(PhoneWindowAO.aj:149)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526b(PhoneWindowAO.aj:153)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1754)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2800)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2383)
        at android.view.View.dispatchPointerEvent(View.java:9527)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4417)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4283)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3734)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3787)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3753)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3761)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3734)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3787)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3753)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3761)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3937)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3734)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3787)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3753)
    	at android.view.ViewRootImp`

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.agora.openvcall, PID: 2681
    java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
        at java.util.ArrayList.get(ArrayList.java:310)
        at io.agora.openvcall.ui.layout.GridVideoViewContainerAdapter.getItem(GridVideoViewContainerAdapter.java:92)
        at io.agora.openvcall.ui.layout.GridVideoViewContainer.getItem(GridVideoViewContainer.java:101)
        at io.agora.openvcall.ui.CallActivity.onBigVideoViewDoubleClicked(CallActivity.java:186)
        at io.agora.openvcall.ui.CallActivity.access$100(CallActivity.java:56)
        at io.agora.openvcall.ui.CallActivity$1.onItemDoubleClick(CallActivity.java:153)
        at io.agora.propeller.ui.RecyclerItemClickListener$1.onDoubleTap(RecyclerItemClickListener.java:62)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:563)
        at io.agora.propeller.ui.RecyclerItemClickListener.onInterceptTouchEvent(RecyclerItemClickListener.java:75)
        at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2932)
        at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2978)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2150)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2422)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1754)
        at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526bproceed(PhoneWindowAO.aj:149)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526b(PhoneWindowAO.aj:153)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1754)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2800)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2383)
        at android.view.View.dispatchPointerEvent(View.java:9527)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4417)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4283)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3734)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3787)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3753)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3761)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3734)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3787)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3753)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3761)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3937)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3734)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3787)
    	at android.view.ViewRootImpl$InputStage.f`

**Comment by yoreland** [comment]
Hi @ArcherEmiya05 seems I can't reproduce your issue by just double click on video view.
Can you provide detailed information, like how many user exists in the channel when issues reproduced? If it is possible can you provide a video for the issue?
