### ISSUE TITLE
One-to-One-Video/Agora-Android-Tutorial-1to1 text relocation error

### ISSUE THREAD

**Issue by achirun** [AgoraIO/Basic-Video-Call#25]
We have the crashes with our app which uses the agora video calls on the Android tables with Intel Atom processors (x86) (e.g. [ALCO RCT6973W43](https://browser.geekbench.com/geekbench3/8306245) with Android 6.0.1). 

> java.lang.UnsatisfiedLinkError: dlopen failed: : has text relocations 
java.lang.Runtime.loadLibrary()Runtime.java:372 
java.lang.System.loadLibrary()System.java:1076 
io.agora.rtc.internal.RtcEngineImpl.initializeNativeLibs()RtcEngineImpl.java:272 
io.agora.rtc.RtcEngine.create()RtcEngine.java:24 

I've also tested the Agora-Android-Tutorial-1to1 on the emulators and got the next error:

> --------- beginning of crash
2019-01-31 10:49:59.076 6081-6081/io.agora.tutorials1v1vcall E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.agora.tutorials1v1vcall, PID: 6081
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/io.agora.tutorials1v1vcall-OJzE5g_omQBLFVYHYnIE1w==/lib/x86/libagora-rtc-sdk-jni.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.agora.rtc.internal.RtcEngineImpl.initializeNativeLibs(RtcEngineImpl.java:272)
        at io.agora.rtc.RtcEngine.create(RtcEngine.java:24)
        at io.agora.tutorials1v1vcall.VideoChatViewActivity.initializeAgoraEngine(VideoChatViewActivity.java:187)
        at io.agora.tutorials1v1vcall.VideoChatViewActivity.initAgoraEngineAndJoinChannel(VideoChatViewActivity.java:74)
        at io.agora.tutorials1v1vcall.VideoChatViewActivity.onCreate(VideoChatViewActivity.java:69)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-01-31 10:49:59.102 6081-6081/io.agora.tutorials1v1vcall I/Process: Sending signal. PID: 6081 SIG: 9

**Could you help us with this issue?**

**Comment by brianxcli** [comment]
X86 text relocation issue was fixed in 2.3.2 and above available both from our official download page and jcenter.

**Comment by achirun** [comment]
I've just tested with the updated library (v2.3.3) and it's all working. Thanks a lot ))
